---
title: "Title of the report/project" 
author: 
  - FirstName LastName, Illinois Institute of Technology^[This is a technical report required for Fellows who complete an approved and funded project for [Socially Responible Modeling, Computation, and Design](https://www.soremo.org), an initiative at Illinois Tech, [Contact the author](mailto:FirstName.LastName@hawkiit.edu).] 
date: "Spring 2021 SoReMo Fellowship Project Final Technical Report"
output: 
  rmdformats::material:
    cards: false
css: soremo.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,comment = '', fig.width = 3, fig.height = 3
  )
```

---

# Formatting

We use Markdown to publish the final reports in [SoReMo](http://journals.library.iit.edu/index.php/Soremo/). 

> What is the format of this document?

This document  was created using `R Markdown`. You can read more about it [here](https://www.markdownguide.org/getting-started/) and check out a [cheat sheet here](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf), which will guide you through installing RStudio, and from there the moment you create  a new `.Rmd` document, it will be a  working template to start from.  If you are used to using `LaTeX`, no worries: it can be embedded into `Markdown`, with overall simpler formatting. I hope you find this useful! 

# Workflow

Some details on the 
submission / review / revision / production / publication workflow 


# Guidelines

What to write in the report? Check out the tech report section in this document: [resources for presentations and reports](https://htmlpreview.github.io/?https://github.com/Sondzus/SoReMo/blob/main/SoReMo-ResourcesForFellows.html)

---


# License

The template was created for publication in [SoReMo](http://journals.library.iit.edu/index.php/Soremo/). 

**The authors will retain the copyright upon the publication of this document.** This technical report has undergone a two-stage blind review process (by faculty and students from Illinois Tech) and has been accepted as a final report by SoReMo. The publication of this report is a deliverable requirement for all SoReMo Fellows; it is not equivalent to an academic publication, rather to a tech report / preprint. 

For guidelines what to write see the "resources for fellows" document. 


    
    
    <!-- # https://stackoverflow.com/questions/41030477/changing-chunk-background-color-in-rmarkdown--> 