---
title: "Technical report template document" 
subtitle: "Spring/Fall 20XX SoReMo Fellowship Project Final Technical Report"
author: 
  - FirstName  LastName, Illinois Institute of Technology^[[Contact the author](mailto:YOUREMAILHERE@hawk.iit.edu).] 
output:
  pdf_document: 
    toc: true
    toc_depth: 1
    fig_width: 2
    fig_caption: true
urlcolor: cyan
linkcolor: cyan
bibliography: mybiblio.bib
---




# Abstract 
Write your abstract in plain English. Why did you do this project? What did it accomplish? 

# Background or introduction
Tell us more  about the *context* of your project. Make sure to cite other work on which you're building. Line
breaks
do
not
matter unless there is a blank line between two lines of text  - then it's a new paragraph,

like it just happened here. 

# Another section, such as technical details 
What exactly did you do? Data, figures, etc. 

## Here is a subsection
you can focus on a specific aspect. 

> Here is a quote. 

### Here is a sub-subsection with lists 

And in it I want to include a list:

* item 1
* item 2
* but there often needs to be a blank line before a bulleted list, for Markdown to recognize it and format as a list!, 

or a numbered, nested one:

1) i like
2) lists so much
    * but they have to be 
    * easy to read. 
        * indentation does the trick. 
 


# Future work 
What might be a cool followup to this project? how would you imagine its impact? 

# Executive summary, or action proposal
Specific things you propose to be done, action items as a direct result of your project; *or* specific outcomes already observed. 
The project's  impact on key stakeholders, whom you've clearly identified. 

# License

The template was created for publication in [SoReMo](http://journals.library.iit.edu/index.php/Soremo/). 

Authors of the reports retain copyright of their work. 

This document is created by [Sonja Petrovic](www.sonjapetrovicstats.com) for [SoReMo](www.soremo.org) and is released under the same licence as the parent [folder](https://sondzus.github.io/SoReMo/) on Github. 

# Acknowledgements 

Optional section. 
The Acknowledgements should contain text acknowledging non-author contributors. Acknowledgements should be brief, and should not include thanks to anonymous referees and editors or effusive comments. If applicable, additional grant  numbers  or supporting agencies may be acknowledged.
    
    
# References 

If you are able to knit your own HTML/PDF from Markdown, leave this section blank. The bibliography will be created from your file `mybiblio.bib.` If you are uncomfortable, add your references here in style as close to BibTex as possible, and the editors will help with the rest.  
